akka.http.server.idle-timeout = 300s

stiltweb{

	admins = []
	
	auth = ${authPub.ICOS} //substituted from cpauth core config

	metDataDirectory = "/disk/data/stilt/Input/Metdata/Europe2"

	stateDirectory   = "/disk/data/stiltweb"

	netcdf {
		dateVars = ["date", "mtime", "time", "tstep"]
		latitudeVars = ["latitude", "lat"]
		longitudeVars = ["longitude", "lon"]
		elevationVars = ["nz"]
	}

	slotStepInMinutes = 180

	matomo {
		url = "https://matomo.icos-cp.eu/matomo.php"
		siteId = 8
		authToken = ""
		baseStiltUrl = "https://stilt.icos-cp.eu"
	}
}
